---
AllCops:
  TargetRubyVersion: "2.1"
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true

Naming/FileName:
  Enabled: false

Style/Documentation:
  Enabled: true
  Exclude:
    - 'lib/formatter/date/version.rb'
    - 'test/**/*'

Style/DateTime:
  Enabled: true
  Exclude:
    - 'test/**/*'

# Method
Style/SingleLineMethods:
  AllowIfMethodIsEmpty: false

Style/FormatString:
  EnforcedStyle: percent

# Hash
Layout/IndentHash:
  EnforcedStyle: consistent

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space

# Parameter
Metrics/ParameterLists:
  Max: 3
  CountKeywordArgs: true
